# Generated by Django 3.1.4 on 2021-03-04 03:43

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='username',
            field=models.CharField(error_messages={'max_length': 'ユーザー名の文字数の上限は30です', 'unique': 'そのユーザー名は既に使用されています'}, max_length=30, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator(message='ユーザー名に使用できるの記号は@/./+/-/_のみです')]),
        ),
    ]
